### ISSUE TITLE
Code Sample!

### ISSUE THREAD

**Issue by malkurwi** [MercuryPay/PDCX.VB6#1]
Hello there,

Is there any code sample of how to send the EBT transaction (Process Transaction)?
Thanks!

**Comment by dourada** [comment]
Greetings,

Please see the Samples folder in this repository.  The code pattern is the same as demonstrated in the sample code but you will use a slightly different XML "packet".  Here's the link to the EBT sample directory:  https://github.com/MercuryPay/PDCX.VB6/tree/master/Samples/EBT.

If you have not already been assigned an implementation consultant please feel free to reach out to our team:  integrationteam@mercurypay.com.

Thanks!
